version: "3.8"

networks:
  ai-translate-dev:
    driver: bridge

services:
  translate-app-dev:
    container_name: translate-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
      - .env.development
    volumes:
      - .:/app
    restart: always
    ports:
      - 3005:3005
    networks:
      - ai-translate-dev
    depends_on:
      mysql:
        condition: service_healthy
      
  mysql:
    image: mysql:8.0
    container_name: translate-app-mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
    # volumes:
    #   - ./docker/data/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=translate
      # - MYSQL_USER=translate
      # - MYSQL_PASSWORD=qwertyuiop
    ports:
      - '3308:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P3306']
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - ai-translate-dev
